workflows:
  ios-build:
    name: iOSアプリのビルド
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: 必要な道具の準備
        script: npm install
      - name: Webアプリのデータ作成
        script: npm run build
      - name: iPhone用にデータを変換
        script: npx cap sync ios
      - name: iOSアプリの完成品を作る
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO